#!/usr/bin/env node

// require necessary packages
var fs = require("fs");
var spawn = require("child_process").spawn

// setup file path names
var configPath = process.argv[2];
var simpleConfigPath = configPath + ".txt";

// load in configuration, which is just an array of peers
var peers = require(configPath);

// create a simple text file for go to use
var simpleConfig = [];
peers.forEach(function(peer) {
  simpleConfig.push(peer.ip + ":" + peer.port);
});
var simpleConfigData = simpleConfig.join("\n");
fs.writeFileSync(simpleConfigPath, simpleConfigData)

// spin up each peer
peers.forEach(function(peer, index) {
  if (peer.ip == "127.0.0.1") {
    spawn("go", ["run", "server/server.go", simpleConfigPath, index]);
  }
});
console.log("running...")
